Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
      - 'db/**/*'
      - 'bin/**/*'
      - 'Gemfile'
      - 'spec/**/*'
      - 'config/**/*'
      - 'test/**/*'

  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Style/FrozenStringLiteralComment:
  Enabled: false